# Generated by Django 5.1.3 on 2024-11-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("reservation_date", models.DateTimeField()),
                ("guests_count", models.PositiveIntegerField()),
                ("special_request", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
