# Generated by Django 5.1.3 on 2024-11-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_reservation_customer_email_reservation_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
