# Generated by Django 5.1.3 on 2024-11-13 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_reservation_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="confirmed",
        ),
    ]
